version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: cat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: cat_search_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cat-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped

  # Node.js Backend
  backend:
    build:
      context: ./backend/Api_Cats
    container_name: cat-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/Api_Cats/.env
    volumes:
      - ./backend/Api_Cats:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  # Vue Frontend
  frontend:
    build:
      context: ./frontend/front-end_api_cats
    container_name: cat-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/front-end_api_cats:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://192.168.1.72:3000   
      - VITE_HOST=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  default:
    driver: bridge